services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}

  postgres:
    image: postgis/postgis:13-3.1
    platform: ${PLATFORM}
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
