name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "latest"
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          project_id: nth-highlander-423208-r5
          export_default_credentials: true

      - name: Authenticate with Google Cloud SDK
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCLOUD_KEY }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy hotel-list \
            --quiet \
            --runtime=nodejs18 \
            --trigger-http \
            --region=us-east1 \
            --entry-point=getHotels \
            --source=.
